version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "roadshow-2022"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15ld3uo3uut2x"
s3_prefix = "roadshow-2022"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
